#!/bin/sh

# ステージに追加されたフォーマット対象拡張子をフォーマットかける。
FILES=$(git diff --name-only --cached --diff-filter=ADM -- "*.js" "*.jsx" "*.ts" "*.tsx")
if [ -n "$FILES" ]; then
  npx prettier --write $FILES
fi

exit 0