#!/bin/sh

# masterへの直コミットは禁止
CURRENT_BRANCH=$(git branch --show-current)
if [ "$CURRENT_BRANCH" = "master" ]; then
  echo "error: restrict commit on master branch"
  exit 1
fi

# ステージに追加されたフォーマット対象拡張子をフォーマットかける。
FILES=$(git diff --name-only --cached --diff-filter=ADM -- "*.js" "*.jsx" "*.ts" "*.tsx")
if [ -n "$FILES" ]; then
  npx prettier --write $FILES
  git add $FILES
fi

exit 0